
package Panels;

import Entities.JoinedTables.ToolSupplier;
import Entities.Supplier;
import Entities.Tool;
import Services.ToolService;
import Services.ToolSupplierService;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class CreateToolSupplier extends javax.swing.JPanel {

    Supplier supplier;
    List<Tool> tools;
    ToolSupplier toolSupplier;
    String[] currencies = {"PHP", "USD", "EUR", "JPY", "GBP", "KRW", "SGD", "GBP", "CHF", "CAD", "AUD", "NZD", "ZAR"};
    
    /**
     * Creates new form CreateToolSupplier
     */
    public CreateToolSupplier() {
        initComponents();
    }

    public CreateToolSupplier(Supplier supplier) {
        initComponents();
        this.supplier = supplier;
        initializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbxToolCode = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxDescription = new javax.swing.JComboBox<>();
        lblSupplierName = new javax.swing.JLabel();
        txtUnit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCurrency = new javax.swing.JComboBox<>();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Price:  ");
        jLabel6.setPreferredSize(new java.awt.Dimension(131, 22));

        cbxToolCode.setEditable(true);
        cbxToolCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxToolCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxToolCodeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Description:  ");
        jLabel3.setPreferredSize(new java.awt.Dimension(131, 22));

        txtPrice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tool Code:  ");

        cbxDescription.setEditable(true);
        cbxDescription.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDescriptionActionPerformed(evt);
            }
        });

        lblSupplierName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtUnit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Supplier Name:  ");
        jLabel1.setPreferredSize(new java.awt.Dimension(131, 22));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Unit:  ");
        jLabel5.setPreferredSize(new java.awt.Dimension(131, 22));

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Currency:  ");
        jLabel7.setPreferredSize(new java.awt.Dimension(131, 22));

        txtCurrency.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSupplierName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrice))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCurrency, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxToolCode, 0, 391, Short.MAX_VALUE)
                            .addComponent(cbxDescription, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUnit))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSupplierName))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxToolCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxToolCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxToolCodeActionPerformed
        if(cbxToolCode.getSelectedIndex() > -1) {
            Tool tool = tools.get(cbxToolCode.getSelectedIndex());
            cbxDescription.setSelectedItem(tool.getDescription());
            txtUnit.setText(tool.getUnit());
        }
        txtUnit.setEnabled(cbxToolCode.getSelectedIndex() == -1);
    }//GEN-LAST:event_cbxToolCodeActionPerformed

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !(evt.getKeyChar() == '.')){
            evt.consume();
        }
    }//GEN-LAST:event_txtPriceKeyTyped

    private void cbxDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDescriptionActionPerformed
        if(cbxDescription.getSelectedIndex() > -1) {
            Tool tool = tools.get(cbxDescription.getSelectedIndex());
            cbxToolCode.setSelectedItem(tool.getCode());
            txtUnit.setText(tool.getUnit());
        }
        txtUnit.setEnabled(cbxDescription.getSelectedIndex() == -1);
    }//GEN-LAST:event_cbxDescriptionActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        boolean confirmToSave = false;
        Tool tool = new Tool();
        int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to add this item to the supplier?", "CONFIRM TOOL SUPPLIED", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(confirmation == 0) {
            if(cbxDescription.getSelectedIndex() == -1 || cbxToolCode.getSelectedIndex() == -1) {
                boolean confirmToSaveMaterial = false;
                if(ToolService.isExisting("code", cbxToolCode.getSelectedItem().toString())) {
                    JOptionPane.showMessageDialog(null, "Tool Code is already existing, please reformat the data", "EXISTING UNIQUE TOOL IDENTIFIER", JOptionPane.ERROR_MESSAGE);
                } else {
                    int saveAnyway = 0;
                    if(ToolService.isExisting("description", cbxDescription.getSelectedItem().toString())) {
                        saveAnyway = JOptionPane.showConfirmDialog(null, "Tool Description is already existing, DO YOU WISH TO SAVE IT ANYWAY?", "CONFIRM SAVE EXISTING DATA", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
                    }
                    if(saveAnyway == 0) {
                        confirmToSaveMaterial = true;
                    }
                }
                if(confirmToSaveMaterial) {
                    tool.setCode(cbxToolCode.getSelectedItem().toString());
                    tool.setDescription(cbxDescription.getSelectedItem().toString());
                    tool.setUnit(txtUnit.getText().trim());
                    if(ToolService.saveTool(tool)) {
                        confirmToSave = true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to save tool, please contact technical support.", "SAVING FAILED", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                tool = tools.get(cbxDescription.getSelectedIndex());
                confirmToSave = true;
            }
            if(confirmToSave) {
                toolSupplier = new ToolSupplier();
                toolSupplier.setSupplier(supplier);
                toolSupplier.setTool(tool);
                toolSupplier.setCurrency(txtCurrency.getSelectedItem().toString());
                toolSupplier.setPrice(BigDecimal.valueOf(Double.parseDouble(txtPrice.getText())));
                if(ToolSupplierService.saveToolSupplier(toolSupplier)) {
                    JOptionPane.showMessageDialog(null, "Tool SUPPLIER SUCCESSFULLY SAVED!!");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to save Material Supplier, Please Contact Technical Support", "TRANSACTION FAILED", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbxDescription;
    private javax.swing.JComboBox<String> cbxToolCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSupplierName;
    private javax.swing.JComboBox<String> txtCurrency;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables

    private void initializeData() {
        lblSupplierName.setText(supplier.getName());
        AutoCompleteDecorator.decorate(cbxDescription);
        AutoCompleteDecorator.decorate(cbxToolCode);
        tools = ToolService.findByNotInSupplier(supplier);
        DefaultComboBoxModel toolsCodeModel = new DefaultComboBoxModel();
        DefaultComboBoxModel descriptionModel = new DefaultComboBoxModel();
        tools.forEach(tool -> {
            toolsCodeModel.addElement(tool.getCode());
            descriptionModel.addElement(tool.getDescription());
        });
        SwingUtilities.invokeLater(() -> {
            cbxToolCode.setModel(toolsCodeModel);
            cbxDescription.setModel(descriptionModel);
            txtCurrency.setModel(new DefaultComboBoxModel(currencies));
        });
    }

    public ToolSupplier getToolSupplier() {
        return toolSupplier;
    }
    
}
